version: "3.8"

services:
  jada-server:
    entrypoint: ['./scripts/wait_for_deps.sh', './scripts/start.sh']
    image: astongemmy/jada:v1
    working_dir: /app
    build: .
    volumes:
      - ./.venv:/app/.venv/
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP}
      - PORT=${PORT}
  
  redis:
    image: redis:latest