#!/bin/bash

source ./scripts/utils

echo "${green}Installing frontend packages.${clear}"

cd ./frontend && npm install

echo "${green}Installing backend packages.${clear}"

cd .. && cd ./backend

python3 -m venv .venv && source .venv/bin/activate

pip install -r requirements.txt --upgrade

echo "${green}Packages installed successfully!${clear}"