#!/bin/bash

# Define global variables
green='\033[92m'
clear='\033[0m'
red='\033[31m'

# Ping started backend server
function ping_flask_server() {
  response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/api/v1/user/questions)
  if [ $response -eq 200 ]; then
    return 0  # Server is up and running
  else
    return 1  # Server is not yet ready
  fi
}

# Check if backend server has started within a specified time
start_time=$(date +%s)
timeout=60
function is_server_started() {
  while ! ping_flask_server; do
    current_time=$(date +%s)
    elapsed_time=$((current_time - start_time))
    
    if [ $elapsed_time -ge $timeout ]; then
      return 1
    fi

    sleep 1
  done

  return 0
}