# Workflow to run tests once a push is made, 
name: Tests Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push events
  push:
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-test:
    name: Run Series of Application Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Start running tests
        run: echo 'Installed application packages...'
        run: sh ./scripts/install
        run: echo 'Packages installed successfully!'
        run: sh ./scripts/test
        run: echo 'All tests ran successfully!'
